import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "next practice",
  description: "Generated by create next 14 app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <nav className="m-[20px] gap-[20px] flex">
          <Link href="/">메인</Link>
          <Link href="/mypage">마이페이지</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
